name: iOS CD

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: import ProvisioningProfile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/flutter-ios-cd-practice-app-store.mobileprovision

      - name: import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}

      - name: install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.0'
          channel: 'stable'

      - name: cache pub
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{runner.OS}}-flutter-install-cache

      - name: flutter dependencies install
        run: flutter pub get

      - name: cache pods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: pod install
        if: steps.cache-cocoapods.outputs.cache-hit != 'true'
        run: |
          cd ios/
          flutter pub get
          pod install

      - name: build ipa
        run: flutter build ipa --export-options-plist=ExportOptions.plist
